from __future__ import annotations

from pathlib import Path

from job_agent.cli import run_source_now
from job_agent.io.json_store import read_json
from job_agent.services.single_source_run_service import SingleSourceRunResult, SingleSourceRunService


def test_single_source_run_missing_source_returns_not_found(template_project: Path) -> None:
    result = SingleSourceRunService(template_project).run("missing")

    assert result.status == "not_found"
    assert not result.run_id


def test_single_source_run_disabled_source_does_not_run(template_project: Path) -> None:
    _write_local_sources(template_project, first_enabled=False)

    result = SingleSourceRunService(template_project).run("first-source")

    assert result.status == "disabled"
    assert not result.run_id
    assert not (template_project / "output" / "runs" / "runs.json").exists()


def test_single_source_run_enabled_source_writes_packages_and_source_id(template_project: Path) -> None:
    _write_local_sources(template_project)

    result = SingleSourceRunService(template_project).run("first-source")

    assert result.status == "completed"
    assert result.source_id == "first-source"
    assert result.extracted_job_count == 1
    assert result.package_count == 1
    assert result.run_id
    assert result.run_detail_url == f"/runs/{result.run_id}"
    indexes = list((template_project / "output").glob("*/*/index.json"))
    assert len(indexes) == 1
    index = read_json(indexes[0], {})
    assert index["source_id"] == "first-source"
    assert index["source"] == "First Source"
    assert "Second Source" not in index["source"]
    assert result.packages[0].source_id == "first-source"
    assert result.packages[0].package_path.endswith("index.json")


def test_single_source_run_runs_only_selected_source(template_project: Path) -> None:
    _write_local_sources(template_project)

    result = SingleSourceRunService(template_project).run("second-source")

    assert result.extracted_job_count == 1
    indexes = list((template_project / "output").glob("*/*/index.json"))
    assert len(indexes) == 1
    index = read_json(indexes[0], {})
    assert index["source_id"] == "second-source"
    assert index["source"] == "Second Source"


def test_single_source_run_preserves_source_warnings(template_project: Path) -> None:
    (template_project / "sources" / "recruiting-sites.yaml").write_text(
        "sources:\n"
        "  - name: Broken Source\n"
        "    source_id: broken-source\n"
        "    type: unsupported\n"
        "    enabled: true\n",
        encoding="utf-8",
    )

    result = SingleSourceRunService(template_project).run("broken-source")

    assert result.status == "completed_with_warnings"
    assert result.extracted_job_count == 0
    assert result.package_count == 0
    assert any("Unsupported source type" in warning for warning in result.warnings)


def test_cli_run_source_prints_run_result(monkeypatch, capsys) -> None:
    class FakeService:
        def run(self, source_id):
            assert source_id == "first-source"
            return SingleSourceRunResult(
                source_id="first-source",
                source_name="First Source",
                source_type="local_yaml",
                status="completed",
                run_id="run-1",
                extracted_job_count=1,
                package_count=1,
                strong_matches=1,
                exploratory_matches=0,
                run_detail_url="/runs/run-1",
            )

    monkeypatch.setattr("job_agent.services.single_source_run_service.SingleSourceRunService", lambda: FakeService())

    run_source_now("first-source")

    output = capsys.readouterr().out
    assert "Source id: first-source" in output
    assert "Run id: run-1" in output
    assert "Packages written: 1" in output
    assert "Materials were not generated by default" in output


def _write_local_sources(root: Path, *, first_enabled: bool = True) -> None:
    (root / "sources" / "recruiting-sites.yaml").write_text(
        "sources:\n"
        "  - name: First Source\n"
        "    source_id: first-source\n"
        "    type: local_yaml\n"
        "    path: jobs/raw/first.yaml\n"
        f"    enabled: {'true' if first_enabled else 'false'}\n"
        "  - name: Second Source\n"
        "    source_id: second-source\n"
        "    type: local_yaml\n"
        "    path: jobs/raw/second.yaml\n"
        "    enabled: true\n",
        encoding="utf-8",
    )
    (root / "jobs" / "raw" / "first.yaml").write_text(
        "jobs:\n"
        "  - title: SAP ABAP RAP Consultant\n"
        "    company: Recruiter\n"
        "    url: https://example.com/first\n"
        "    location: Remote\n"
        "    description: Strong ABAP RAP CDS OData Gateway S/4HANA contract role.\n",
        encoding="utf-8",
    )
    (root / "jobs" / "raw" / "second.yaml").write_text(
        "jobs:\n"
        "  - title: SAP ABAP RAP Integration Consultant\n"
        "    company: Recruiter\n"
        "    url: https://example.com/second\n"
        "    location: Remote\n"
        "    description: Strong ABAP RAP CDS OData Gateway S/4HANA integration contract role.\n",
        encoding="utf-8",
    )
